// <auto-generated />
using System;
using MeetingRoomApi.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeetingRoomApi.Migrations
{
    [DbContext(typeof(MeetingRoomDbContext))]
    partial class MeetingRoomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MeetingRoomApi.Models.MeetingRoom", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnName("MeetingRoom_Id");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("MeetingRooms");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            RoomName = "Main Room"
                        });
                });

            modelBuilder.Entity("MeetingRoomApi.Models.Member", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Member_Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(25);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("ReservationColorCode")
                        .HasMaxLength(15);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "Receb",
                            Password = "$2b$10$x8nolylA9yauFqjiPQ6Z2O9AvLxfO.v1DrWEv01SiwfnsSJGgO57C",
                            Surname = "Qarayev",
                            UserName = "Rajab97"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "Test",
                            Password = "$2b$10$VKBd0nO74ctg1OY3TdukneS2ymewgbgWjg7PM4ZuLXtp2GPXl.aNe",
                            Surname = "Test",
                            UserName = "Test123"
                        });
                });

            modelBuilder.Entity("MeetingRoomApi.Models.Role", b =>
                {
                    b.Property<byte>("Id");

                    b.Property<string>("Name")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = (byte)2,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("MeetingRoomApi.Models.RoomReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RoomReservation_Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<byte>("MeetingRoomId")
                        .HasColumnName("MeetingRoom_Id");

                    b.Property<short>("MemberId")
                        .HasColumnName("Member_Id");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("date");

                    b.Property<short>("TimeId")
                        .HasColumnName("Time_Id");

                    b.Property<string>("Title")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("ReservationDate", "TimeId", "MeetingRoomId");

                    b.HasIndex("MeetingRoomId");

                    b.HasIndex("MemberId");

                    b.HasIndex("TimeId");

                    b.ToTable("RoomReservations");
                });

            modelBuilder.Entity("MeetingRoomApi.Models.Time", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ValidRoomTime_Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(0)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(0)");

                    b.HasKey("Id");

                    b.HasAlternateKey("StartTime", "EndTime");

                    b.ToTable("ValidRoomTimes");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = (short)2,
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            Id = (short)3,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = (short)4,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 30, 0, 0)
                        },
                        new
                        {
                            Id = (short)5,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            Id = (short)6,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            StartTime = new TimeSpan(0, 11, 30, 0, 0)
                        },
                        new
                        {
                            Id = (short)7,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            Id = (short)8,
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            StartTime = new TimeSpan(0, 12, 30, 0, 0)
                        },
                        new
                        {
                            Id = (short)9,
                            EndTime = new TimeSpan(0, 14, 30, 0, 0),
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = (short)10,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            StartTime = new TimeSpan(0, 14, 30, 0, 0)
                        },
                        new
                        {
                            Id = (short)11,
                            EndTime = new TimeSpan(0, 15, 30, 0, 0),
                            StartTime = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = (short)12,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 15, 30, 0, 0)
                        },
                        new
                        {
                            Id = (short)13,
                            EndTime = new TimeSpan(0, 16, 30, 0, 0),
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = (short)14,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 16, 30, 0, 0)
                        },
                        new
                        {
                            Id = (short)15,
                            EndTime = new TimeSpan(0, 17, 30, 0, 0),
                            StartTime = new TimeSpan(0, 17, 0, 0, 0)
                        },
                        new
                        {
                            Id = (short)16,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StartTime = new TimeSpan(0, 17, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("MeetingRoomApi.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("MemberId");

                    b.Property<byte>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MemberId = (short)1,
                            RoleId = (byte)2
                        },
                        new
                        {
                            Id = 2,
                            MemberId = (short)2,
                            RoleId = (byte)3
                        });
                });

            modelBuilder.Entity("MeetingRoomApi.Models.RoomReservation", b =>
                {
                    b.HasOne("MeetingRoomApi.Models.MeetingRoom", "MeetingRoom")
                        .WithMany("RoomReservations")
                        .HasForeignKey("MeetingRoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MeetingRoomApi.Models.Member", "Member")
                        .WithMany("RoomReservations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MeetingRoomApi.Models.Time", "Time")
                        .WithMany("RoomReservations")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MeetingRoomApi.Models.UserRole", b =>
                {
                    b.HasOne("MeetingRoomApi.Models.Member", "Member")
                        .WithMany("UserRoles")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MeetingRoomApi.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
